### PR TITLE
Fix repeated case-insensitive ASCII match

### LINKED ISSUE #785: Case-insensitive regex with repetitions does not match uppercase characters correctly
### Description

In case-insensitive regular expressions containing repetitions (`+` or `*`), the repeated part is not matched correctly against differently cased characters in the string to be searched.

### Reproduction

```swift
func test(_ pattern: Regex<Substring>, on s: String) throws {
    print("\(s) contains \(try pattern.firstMatch(in: s)?.output ?? "no match")")
}

for s in ["ab", "Ab"] {
    try test(#/ab/#.ignoresCase(), on: s)
    try test(#/a*b/#.ignoresCase(), on: s)
    try test(#/a+b/#.ignoresCase(), on: s)
}
```

This snippet outputs

```
ab contains ab
ab contains ab
ab contains ab
Ab contains Ab
Ab contains b
Ab contains no match
```

### Expected behavior

I would expect it to output

```
ab contains ab
ab contains ab
ab contains ab
Ab contains Ab
Ab contains Ab
Ab contains Ab
```

### Environment

swift-driver version: 1.115 Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
Target: arm64-apple-macosx15.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by natecook1000**
The optimized bytecode for matching repetition of a single character overlooks case insensitivity. This resolves that by falling back to use an ASCII bitset when doing a case-insensitive match of a cased character.

Fixes #785.

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test

**Comment by natecook1000** [comment]
@swift-ci Please test

File: Tests/RegexTests/MatchTests.swift [hunk 1]
```diff
@@ -2193,6 +2193,25 @@ extension RegexTests {
       ("cafe", true),
       ("CaFe", true),
       ("EfAc", true))
+    
+    matchTest(
+      #"(?i)a+b"#,
+      ("ab", true),
+      ("Ab", true),
+      ("aB", true),
+      ("AB", true))
```
Comment (milseman) [inline Tests/RegexTests/MatchTests.swift:2202]: Could you add some more test cases, where there are multiple mixed-case As?

File: Tests/RegexTests/MatchTests.swift [hunk 2]
```diff
@@ -2193,6 +2193,25 @@ extension RegexTests {
...
+    matchTest(
+      #"(?i)[a]?b"#,
+      ("ab", true),
+      ("Ab", true),
+      ("aB", true),
+      ("AB", true))
```
Comment (milseman) [inline Tests/RegexTests/MatchTests.swift:2214]: Could you try a bounded quantification test case?

**Review by milseman — APPROVED** [review]
LGTM! Good fix. I'd like a few more test cases for this, which can come in a later PR if needed.

**Comment by natecook1000** [comment]
@swift-ci Please test

File: Tests/RegexTests/MatchTests.swift (hunk 2 above)
Comment (jdberry) [reply Tests/RegexTests/MatchTests.swift]: Can you also add test cases for optional characters, which are also broken? See https://github.com/swiftlang/swift/issues/78155
